In [1]:
#Arrays are fundamental data structures in any programming language.
#They represent objects, the objects in a array are call array elements.

#The different between the list and a array, all the array elements must be the same data type.
#E.g. all integers or floats. List is difference; list may contain integer string another string and so on.


In [7]:
import numpy as np # the Scientific library 

In [11]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [12]:
#NumPy n-dimensional array = ndarray
#An ndarray is always homogenous. Should be same data type and interpreted in the same way.

#I need to organise the array are as the same amount of element and as the same data type.

#array is a function for certain method for certain class.
#NumPy is not just a class, is something bigger whole package of several modules and each containing classes on their on.

#np.array is the way to apply array function, takes a few lists as arguments and return a data structures in it.
#array() - returns a data structure in the NumPy array format.


In [14]:
a.shape

(2, 4)

In [15]:
# a.shape # to obtain the shape. The array has 2 rows and 4 colum

In [16]:
#How to access one of the values in an array.
#type the number of row and colum inside the braket e.g. a[1,3]
#count starts at 0. 1st row (actully 2nd row), and 3rd in the colum (actully 4th )
 

In [18]:
a[1,3]

7

In [19]:
#To change value in array, designate the value = to the value you want to change. 
#a[1,2]=8


In [20]:
a[1,2]=8
a

array([[0, 1, 2, 3],
       [4, 5, 8, 7]])

In [21]:
#a single value in the [] e.g. a[0]. It will extract the zero row.

In [22]:
a[0]

array([0, 1, 2, 3])

In [23]:
a[1]

array([4, 5, 8, 7])

In [24]:
#Why arrays are important and how can they help us in analysis financal data.
#Array is the data structure that will organize values into vectors matrices and other multidimensional object.

#A vector is an object that has both magnitude and direction. 
#Can display on cartesian plane.
#Can be written in python as numpy array with single list 
#b=np.array([3,5])


In [26]:
b=np.array([3,5])
b

array([3, 5])

In [29]:
#{one dimentional array also call a vector
#1D array = vector

#2D array=matrices
#matrices is linear algebra term that finance term that use in almost every calculation.

#Mathematic speak matrices is 2 dimensional array to which many powerful maths operations can be apply.
#These features let you manipulate data and the NumPy array is the Python tools that allow you do that.}
